function [theta,dtheta] = fivebar_theta_func(phi0_sym,dphi0_sym,body_phi,body_dphi)
%FIVEBAR_THETA_FUNC
%    [THETA,DTHETA] = FIVEBAR_THETA_FUNC(PHI0_SYM,DPHI0_SYM,BODY_PHI,BODY_DPHI)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2026-07-09 23:13:33

theta = -body_phi+phi0_sym-pi./2.0;
if nargout > 1
    dtheta = -body_dphi+dphi0_sym;
end
end
