function [L0,phi0] = fivebar_kinematics_func(phi1,phi4)
%FIVEBAR_KINEMATICS_FUNC
%    [L0,PHI0] = FIVEBAR_KINEMATICS_FUNC(PHI1,PHI4)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    2026-07-09 23:13:28

t2 = cos(phi1);
t3 = cos(phi4);
t4 = sin(phi1);
t5 = sin(phi4);
t6 = t2.*1.5e+1;
t7 = t3.*1.5e+1;
t8 = -t5;
t10 = t2.*(3.0./4.0e+1);
t11 = t3.*(3.0./4.0e+1);
t12 = t4.*(3.0./4.0e+1);
t13 = t5.*(3.0./4.0e+1);
t15 = t2.*(3.0./8.0e+1);
t16 = t3.*(3.0./8.0e+1);
t9 = -t6;
t14 = -t10;
t17 = -t13;
t18 = t4+t8;
t19 = t18.^2;
t21 = t7+t9+1.6e+1;
t24 = t12+t17;
t26 = t11+t14+2.0./2.5e+1;
t20 = t19.*2.25e+2;
t23 = t21.^2;
t22 = -t20;
t25 = -t23;
t27 = t20+t23;
t28 = 1.0./sqrt(t27);
t29 = t22+t25+3.136e+3;
t30 = sqrt(t29);
t31 = (t24.*t28.*t30)./2.0;
L0 = sqrt((t15+t16+t31).^2+(t4.*(3.0./8.0e+1)+t5.*(3.0./8.0e+1)+(t26.*t28.*t30)./2.0).^2);
if nargout > 1
    phi0 = atan2(t4.*(3.0./8.0e+1)+t5.*(3.0./8.0e+1)+(t26.*t28.*t30)./2.0,t15+t16+t31);
end
end
